FROM node:slim AS build-stage
WORKDIR /app
COPY package.json ./
RUN npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm config set fetch-timeout 300000 && \
    npm config set fetch-retries 5
RUN npm install
COPY . .
# RUN npm run lint    <-- Commente cette ligne
# ... reste du Dockerfile